### ISSUE TITLE
win环境 npm i 部署依赖问题 无法正常安装mocha模块问题

### ISSUE THREAD

**Issue by Archer456** [macaca-sample/desktop-browser-sample-nodejs#1]
经测试，desktop-browser-sample-nodejs 和 mobile-app-sample-nodejs 均有该问题。  
以上两脚步 在ubuntu或mac环境下，均可正常执行。
但在win环境下  本人是win10
`D:\>cd macaca\desktop-browser-sample-nodejs

D:\macaca\desktop-browser-sample-nodejs>dir
 驱动器 D 中的卷没有标签。
 卷的序列号是 0A87-8753

 D:\macaca\desktop-browser-sample-nodejs 的目录

2017/02/14  12:00    <DIR>          .
2017/02/14  12:00    <DIR>          ..
2017/02/14  11:56               124 .gitignore
2017/02/14  11:56                55 .jshintignore
2017/02/14  11:56               559 .jshintrc
2017/02/14  11:56               167 .npmignore
2017/02/14  11:56               292 .travis.yml
2017/02/14  11:56               123 circle.yml
2017/02/14  11:56                 0 HISTORY.md
2017/02/14  11:56             1,122 LICENSE
2017/02/14  11:59    <DIR>          logs
2017/02/14  11:56    <DIR>          macaca-test
2017/02/14  11:56               561 Makefile
2017/02/14  12:00    <DIR>          node_modules
2017/02/14  12:00               780 package.json
2017/02/14  11:56               468 README.md
              11 个文件          4,251 字节
               5 个目录 131,216,510,976 可用字节

D:\macaca\desktop-browser-sample-nodejs>cd macaca-test

D:\macaca\desktop-browser-sample-nodejs\macaca-test>macaca run -d desktop-browser-sample-nodejs.test.js
>> webdriver sdk launched
D:\nodejs\node-global\node_modules\macaca-cli\lib\run\index.js:44
      throw err;
      ^

Error: Cannot find test framework "mocha" in D:\macaca\desktop-browser-sample-nodejs\macaca-test\node_modules
    at Runner.initFramework (D:\nodejs\node-global\node_modules\macaca-cli\lib\run\index.js:71:13)
    at co.then (D:\nodejs\node-global\node_modules\macaca-cli\lib\run\index.js:41:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

D:\macaca\desktop-browser-sample-nodejs\macaca-test>cd ..

D:\macaca\desktop-browser-sample-nodejs>npm i mocha --save
desktop-browser-sample-nodejs@1.0.0 D:\macaca\desktop-browser-sample-nodejs
`-- mocha@3.2.0

D:\macaca\desktop-browser-sample-nodejs>cd macaca-test

D:\macaca\desktop-browser-sample-nodejs\macaca-test>macaca run -d desktop-browser-sample-nodejs.test.js
>> webdriver sdk launched
D:\nodejs\node-global\node_modules\macaca-cli\lib\run\index.js:44
      throw err;
      ^

Error: Cannot find test framework "mocha" in D:\macaca\desktop-browser-sample-nodejs\macaca-test\node_modules
    at Runner.initFramework (D:\nodejs\node-global\node_modules\macaca-cli\lib\run\index.js:71:13)
    at co.then (D:\nodejs\node-global\node_modules\macaca-cli\lib\run\index.js:41:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

D:\macaca\desktop-browser-sample-nodejs\macaca-test>macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.9.5

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_111`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-23`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.5`

可看到  我正确的执行步骤：
1 git clone 项目
2 到含package.json的项目目录下 执行npm i安装依赖
3 到macaca test 目录下 执行macaca run -d  *** --verbose  报 找不到mocha
4 查看package.json  mocha 已存在在 devDependencies 下

5 尝试 到含package.json的项目目录下 执行npm i mocha --save-dev   重新安装mocha 
   再执行 还是找不到mocha

6 尝试到含package.json的项目目录下 执行npm i mocha --save 安装mocha 到 dependencies  
  再执行 也还是找不到mocha

![image](https://cloud.githubusercontent.com/assets/18392901/22915042/6926a5a4-f2af-11e6-8dd8-4771cf0b96d9.png)

**Comment by Archer456** [comment]
补充  发现package.json里macaca相关的版本过老，所以图片里的macaca-utils  macaca-electron  macaca-wd 已替换成官方最新版  这个应该不影响。

**Comment by Archer456** [comment]
好神奇  我用webstorm2016.3   
1 git clone https://github.com/macaca-sample/mobile-app-sample-nodejs.git
2 修改 package.json   "macaca-utils": "^0.1.9"        "macaca-cli": "^1.1.21",    "macaca-wd": "^1.0.14",  为最新版
3 到含  package.json 的项目目录下执行npm i  安装项目执行依赖
4 到 macaca-test脚本目录下 执行macaca run -d mobile-app-sample.test.js --verbose 报错。
   还是那个mocha模块无法找到
5 我就用webstorm2016.3 打开该项目     选中脚本 右键执行 run  。 
   先要手动开macaca server 然后再执行    居然没报错。。。

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/22918265/6ede063a-f2c4-11e6-9e09-32264f78854f.png)
从具体的 错误来看  这应该是macaca-cli 在win环境下的支持bug  js 某行遇到mocha throw err了。

**Comment by xudafeng** [comment]
npm i mocha -g 不行吗

**Comment by Archer456** [comment]
5 尝试 到含package.json的项目目录下 执行npm i mocha --save-dev 重新安装mocha
再执行 还是找不到mocha

6 尝试到含package.json的项目目录下 执行npm i mocha --save 安装mocha 到 dependencies
再执行 也还是找不到mocha

都试过 不行的

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/445
